### PR TITLE
Add author field to metadata

### PR DESCRIPTION
**Pull request by szabgab**
See https://pydigger.com/docs/author

### CODE REVIEW

**Comment by unnown** [comment]
Please mark as invalid and spam, this is an obvious attempt to get a free t-shirt by 'contributing'(hacktoberfest)
This will also ban the user for trying to abuse the system by doing marginal effort

**Comment by szabgab** [comment]
Wow, someone decided to spam GitHub. Several of my PRs got this comment (but none of the PRs that my projects received). Disregard it. Use your own judgement. I've reported this abuse to GitHub.

**Comment by unnown** [comment]
You reported yourself? good idea tbh

**Comment by tys-hiroshi** [comment]
@szabgab Why do you want to add author field?

**Comment by szabgab** [comment]
That seems to accepted way to indicated the original author of the package. (According to my stats on PyDigger only 1.39% of the packages don't have it and my recent manual sampling showed that the majority of those were created by a company).

**Comment by tys-hiroshi** [comment]
@szabgab 
I knew that author field meaning. but what's your merit?

**Pull request merged**
